### ISSUE TITLE
graccreq.Client is incompatible with recent Pika (1.0.0+)

### ISSUE THREAD

**Issue by jthiltges** [opensciencegrid/gracc-request#77]
Pika 1.0.0+ [changed the signature](https://pika.readthedocs.io/en/stable/version_history.html#id4) of a number of methods, including `basic_consume`.

This leads to an error:

```
Summarizing 2020-09-18T21:49:25.521666 to 2020-09-25T21:49:25.521666
Traceback (most recent call last):
  File "/usr/local/bin/graccsumperiodic", line 33, in <module>
    sys.exit(load_entry_point('graccsum==4.2.0', 'console_scripts', 'graccsumperiodic')())
  File "/usr/local/lib/python3.8/site-packages/graccsum-4.2.0-py3.8.egg/graccsum/periodic_summarizer.py", line 65, in main
  File "/usr/local/lib/python3.8/site-packages/graccsum-4.2.0-py3.8.egg/graccsum/periodic_summarizer.py", line 51, in run
  File "/usr/local/lib/python3.8/site-packages/graccsum-4.2.0-py3.8.egg/graccsum/periodic_summarizer.py", line 36, in runRules
  File "/usr/local/lib/python3.8/site-packages/graccreq/client.py", line 156, in query
    self.channel.basic_consume(self._getControlMessage, self.control_queue)
  File "/usr/local/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 1626, in basic_consume
    validators.require_string(queue, 'queue')
  File "/usr/local/lib/python3.8/site-packages/pika/validators.py", line 15, in require_string
    raise TypeError('%s must be a str or unicode str, but got %r' % (
TypeError: queue must be a str or unicode str, but got <bound method Client._getControlMessage of <graccreq.client.Client object at 0x7fb01ecb0910>>
```

Unfortunately, the argument names changed ([v0.10.0](https://github.com/pika/pika/blob/0.10.0/pika/adapters/blocking_connection.py#L1406) to [v1.0.0](https://github.com/pika/pika/blob/1.0.0/pika/adapters/blocking_connection.py#L1575)), so using keywords alone won't be enough.

How would you prefer to fix this? Three options offhand: require the old version, break backwards compatibility, or add codepaths for both pika versions.

**Comment by djw8605** [comment]
Break backwards compatibility. There’s no reason to support older pika. This daemon is packaged in its own docker container, it controls its environment.
